package com.resumemaster.android.data

import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.resumemaster.android.data.db.AppDatabase
import com.resumemaster.android.data.db.ResumeDao
import com.resumemaster.android.data.db.toResume
import com.resumemaster.android.data.db.toRows
import com.resumemaster.android.models.Resume
import com.resumemaster.android.models.ResumeField
import com.resumemaster.android.models.ResumeSection
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

/**
 * The schema against REAL SQLite.
 *
 * ResumeMappingTest covers the mapping on the JVM by handing `toResume` rows it has sorted itself.
 * That deliberately cannot catch a missing ORDER BY, because the test is doing the ordering. These
 * tests let the DATABASE order the rows, which is the only way to find out whether the queries do.
 *
 * They also check the foreign-key cascade rather than trusting it. Room enables FK enforcement by
 * default, but "by default" is a property of a version, and a silently-disabled cascade would leak
 * every field row of every edit — the file would grow without bound while the app looked correct.
 */
@RunWith(AndroidJUnit4::class)
class ResumeDatabaseTest {

  private lateinit var db: AppDatabase
  private lateinit var dao: ResumeDao

  @Before
  fun open() {
    db = Room.inMemoryDatabaseBuilder(
      ApplicationProvider.getApplicationContext(),
      AppDatabase::class.java,
    ).build()
    dao = db.resumeDao()
  }

  @After
  fun close() = db.close()

  private fun sample(name: String = "Sri Yellela") = Resume(
    id = "r1",
    name = name,
    templateID = "modern",
    sections = listOf(
      ResumeSection(
        id = "s-contact", title = "Contact", order = 9, isVisible = true,
        fields = listOf(
          ResumeField(id = "f-email", label = "Email", value = "a@b.c"),
          ResumeField(id = "f-phone", label = "Phone", value = "+1", isBold = true),
          ResumeField(id = "f-site", label = "Site", value = ""),
        ),
      ),
      ResumeSection(
        id = "s-exp", title = "Experience", order = 7, isVisible = false,
        fields = listOf(
          ResumeField(id = "f-role", label = "Role", value = "SWE"),
          ResumeField(id = "f-dates", label = "Dates", value = "2022-2026"),
        ),
      ),
    ),
  )

  private suspend fun store(resume: Resume) {
    val (r, s, f) = resume.toRows()
    dao.replaceResume(r, s, f)
  }

  @Test
  fun anEmptyDatabaseHasNothingToLoad() = runBlocking {
    assertEquals(0, dao.countResumes())
    assertNull(dao.loadLatestGraph())
  }

  @Test
  fun aStoredResumeComesBackIntact() = runBlocking {
    store(sample())

    val loaded = dao.loadLatestGraph()?.toResume()
    assertNotNull(loaded)
    assertEquals("Sri Yellela", loaded!!.name)
    assertEquals("modern", loaded.templateID)
    assertEquals(listOf("Contact", "Experience"), loaded.sections.map { it.title })
  }

  @Test
  fun theDatabaseOrdersSectionsAndFields() = runBlocking {
    // The ordering claim, with SQLite doing the ordering. `order` was saved as 9 then 7 —
    // descending — so a query relying on insertion luck or on the stale field could pass the JVM
    // test and fail here.
    store(sample())

    val loaded = dao.loadLatestGraph()!!.toResume()
    assertEquals(listOf("Contact", "Experience"), loaded.sections.map { it.title })
    assertEquals(listOf(0, 1), loaded.sections.map { it.order })
    assertEquals(
      listOf("Email", "Phone", "Site"),
      loaded.sections[0].fields.map { it.label },
    )
    assertEquals(listOf("Role", "Dates"), loaded.sections[1].fields.map { it.label })
  }

  @Test
  fun aSecondSaveReplacesRatherThanAccumulating() = runBlocking {
    store(sample())
    store(sample(name = "Edited Name"))

    // One resume, not two, and no duplicated sections. replaceResume deletes before inserting; if
    // it did not, @Insert would throw on the primary key — but a schema using autogenerated ids
    // would instead silently double every section on every keystroke.
    assertEquals(1, dao.countResumes())
    val loaded = dao.loadLatestGraph()!!.toResume()
    assertEquals("Edited Name", loaded.name)
    assertEquals(2, loaded.sections.size)
    assertEquals(3, loaded.sections[0].fields.size)
  }

  @Test
  fun deletingSectionsCascadesToTheirFields() = runBlocking {
    store(sample())
    dao.deleteSectionsOf("r1")

    // Asking for the orphans directly: if the cascade were not enforced, these rows would still be
    // here and nothing else in the app would ever notice.
    val orphans = dao.fieldsOf(listOf("s-contact", "s-exp"))
    assertTrue("field rows outlived their sections — the cascade is not enforced", orphans.isEmpty())
  }

  @Test
  fun anEmptiedResumePersistsAsEmptyAndIsStillTheLatest() = runBlocking {
    store(sample())
    store(sample().copy(sections = emptyList()))

    // The user deleted every section. countResumes() is still 1, so hydration will NOT re-seed over
    // this — which is why it counts resumes rather than checking whether one has content.
    assertEquals(1, dao.countResumes())
    val loaded = dao.loadLatestGraph()!!.toResume()
    assertTrue(loaded.sections.isEmpty())
  }

  @Test
  fun theLatestResumeIsTheMostRecentlyModified() = runBlocking {
    // Distinct SECTION ids as well as distinct resume ids. Two real resumes always differ in both,
    // because every id is a fresh UUID — see the test below for what happens when they do not.
    fun distinct(suffix: String, resumeId: String, name: String, modified: Long) =
      sample(name = name).copy(
        id = resumeId,
        lastModified = modified,
        sections = sample().sections.map { section ->
          section.copy(
            id = section.id + suffix,
            fields = section.fields.map { it.copy(id = it.id + suffix) },
          )
        },
      )

    store(distinct("-old", "r-old", "Older", 1_000L))
    store(distinct("-new", "r-new", "Newer", 2_000L))

    assertEquals(2, dao.countResumes())
    assertEquals("Newer", dao.loadLatestGraph()!!.toResume().name)
  }

  @Test
  fun sectionIdsAreGLOBALLYUniqueAndNotScopedPerResume() = runBlocking {
    // WORTH KNOWING BEFORE "DUPLICATE THIS RESUME" IS BUILT.
    //
    // resume_sections.id is a bare primary key, so a section id is unique across the whole database
    // rather than within its resume. replaceResume only clears the sections of the resume it is
    // given, so storing a second resume that reuses a section id throws SQLITE_CONSTRAINT rather
    // than quietly reparenting or overwriting the row.
    //
    // Nothing in the app can hit this today: every id is a fresh UUID and only one resume exists.
    // A duplicate-resume feature that deep-copies a resume WITHOUT regenerating child ids would hit
    // it immediately, and this test is here so that arrives as a documented constraint rather than
    // as a crash report. Throwing is the right behaviour — the alternatives are a silent overwrite
    // of another resume's section, or a section belonging to two resumes at once.
    store(sample())
    val clash = sample(name = "Copy").copy(id = "r2") // same section ids, different resume

    var threw = false
    try {
      store(clash)
    } catch (e: android.database.sqlite.SQLiteConstraintException) {
      threw = true
    }
    assertTrue("reusing a section id across resumes must fail loudly, not silently", threw)

    // The original is untouched: the transaction rolled back.
    assertEquals(1, dao.countResumes())
    assertEquals("Sri Yellela", dao.loadLatestGraph()!!.toResume().name)
  }
}
