// GENERATED by scripts/generateContractModels.py from contract/mobile-api.v1.json
// (contract version 1.1.1). DO NOT HAND-EDIT -- regenerate instead.
//
// 37 fields. The parser this replaced carried 10, and read 5 of those
// under the wrong (snake_case) names, all of which failed silently to null.

package com.resumemaster.android.data.contract

import org.json.JSONObject

data class ContractJob(
  val applyUrl: String = "",
  val automationTier: String? = null,
  val bucketDomain: String? = null,
  val bucketRole: String? = null,
  val bucketSeniority: String? = null,
  val company: String = "",
  val companyIconUrl: String? = null,
  val contractType: String? = null,
  val description: String = "",
  val directApply: Boolean = false,
  val discoveredAt: Long? = null,
  val disliked: Boolean = false,
  val experienceLevel: String? = null,
  val id: String = "",
  val isActive: Boolean = true,
  val isClearanceRequired: Boolean? = null,
  val isH1bSponsor: Boolean? = null,
  val location: String = "",
  val matchScore: Int? = null,
  val postedAt: String? = null,
  val remote: Boolean = false,
  val requiresWorkAuth: Boolean? = null,
  val salaryCurrency: String? = null,
  val salaryMax: Double? = null,
  val salaryMin: Double? = null,
  val skills: List<String> = emptyList(),
  val source: String = "",
  val sourceLabel: String? = null,
  val sourcePlatform: String = "direct",
  val starred: Boolean = false,
  val summary: String? = null,
  val title: String = "",
  val url: String = "",
  val validThrough: String? = null,
  val via: String? = null,
  val visited: Boolean = false,
  val workplaceType: String? = null,
) {
  companion object {

    /**
     * Decode one row, or return NULL if it has no usable identity.
     *
     * `id` is typed `string` by the contract but is NOT in `required`, so a row may legally
     * arrive without one. Such a row cannot be starred, disliked, applied to or
     * de-duplicated, so it is dropped here rather than rendered as a card that silently does
     * nothing. The caller counts what it dropped instead of discovering the gap later as a
     * total that disagrees with the list.
     */
    fun fromJson(o: JSONObject): ContractJob? {
      val id = o.optString("id", "")
      if (id.isEmpty()) return null
      return ContractJob(
        applyUrl = o.optString("applyUrl", ""),
        automationTier = optStringOrNull(o, "automationTier"),
        bucketDomain = optStringOrNull(o, "bucketDomain"),
        bucketRole = optStringOrNull(o, "bucketRole"),
        bucketSeniority = optStringOrNull(o, "bucketSeniority"),
        company = o.optString("company", ""),
        companyIconUrl = optStringOrNull(o, "companyIconUrl"),
        contractType = optStringOrNull(o, "contractType"),
        description = o.optString("description", ""),
        directApply = o.optBoolean("directApply", false),
        discoveredAt = optLongOrNull(o, "discoveredAt"),
        disliked = o.optBoolean("disliked", false),
        experienceLevel = optStringOrNull(o, "experienceLevel"),
        id = o.optString("id", ""),
        isActive = o.optBoolean("isActive", true),
        isClearanceRequired = optBooleanOrNull(o, "isClearanceRequired"),
        isH1bSponsor = optBooleanOrNull(o, "isH1bSponsor"),
        location = o.optString("location", ""),
        matchScore = optIntOrNull(o, "matchScore"),
        postedAt = optStringOrNull(o, "postedAt"),
        remote = o.optBoolean("remote", false),
        requiresWorkAuth = optBooleanOrNull(o, "requiresWorkAuth"),
        salaryCurrency = optStringOrNull(o, "salaryCurrency"),
        salaryMax = optDoubleOrNull(o, "salaryMax"),
        salaryMin = optDoubleOrNull(o, "salaryMin"),
        skills = stringList(o, "skills"),
        source = o.optString("source", ""),
        sourceLabel = optStringOrNull(o, "sourceLabel"),
        sourcePlatform = o.optString("sourcePlatform", "direct"),
        starred = o.optBoolean("starred", false),
        summary = optStringOrNull(o, "summary"),
        title = o.optString("title", ""),
        url = o.optString("url", ""),
        validThrough = optStringOrNull(o, "validThrough"),
        via = optStringOrNull(o, "via"),
        visited = o.optBoolean("visited", false),
        workplaceType = optStringOrNull(o, "workplaceType"),
      )
    }

    /**
     * A string, or null -- distinguishing ABSENT and JSON null from the empty string.
     *
     * org.json optString() returns "" for a missing key AND for an explicit null, so the
     * previous parser optString(...).ifEmpty { null } collapsed three different facts into
     * one. Checked explicitly here because "" is a legitimate value for several of these
     * fields and must not be laundered into null.
     */
    private fun optStringOrNull(o: JSONObject, key: String): String? =
      if (!o.has(key) || o.isNull(key)) null else o.optString(key, "")

    private fun optBooleanOrNull(o: JSONObject, key: String): Boolean? =
      if (!o.has(key) || o.isNull(key)) null else o.optBoolean(key)

    private fun optIntOrNull(o: JSONObject, key: String): Int? =
      if (!o.has(key) || o.isNull(key)) null else o.optInt(key)

    private fun optLongOrNull(o: JSONObject, key: String): Long? =
      if (!o.has(key) || o.isNull(key)) null else o.optLong(key)

    private fun optDoubleOrNull(o: JSONObject, key: String): Double? =
      if (!o.has(key) || o.isNull(key)) null else o.optDouble(key)

    /** Always a list; [] when absent. The contract guarantees the shape, not the presence. */
    private fun stringList(o: JSONObject, key: String): List<String> {
      val arr = o.optJSONArray(key) ?: return emptyList()
      return (0 until arr.length()).mapNotNull { i ->
        if (arr.isNull(i)) null else arr.optString(i, "").ifEmpty { null }
      }
    }
  }
}
