#!/usr/bin/env python3
"""
Generate the contract-typed Job model from contract/mobile-api.v1.json.

WHY GENERATED. The hand-rolled parser this replaces read five fields under snake_case names
(salary_min, salary_max, salary_currency, posted_at, contract_type) that the server emits in
camelCase. Every one of them resolved through optString().ifEmpty{null} to null, so salary never
rendered, tags were always empty and remote was never labelled -- and NOTHING FAILED. A wrong key
name is invisible to a compiler and invisible to a test that only checks "the call succeeded".
Deriving the field list from the contract makes that class of defect impossible to write by hand.

Run:  python scripts/generateContractModels.py
      python scripts/generateContractModels.py --check     (fail if the output is stale)

The output is committed. It is a build input, not a build step -- keeping codegen out of the Gradle
graph means a contract bump is a reviewable diff rather than a silent behaviour change.
"""

import hashlib
import io
import json
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONTRACT = os.path.join(REPO, 'contract', 'mobile-api.v1.json')
CHECKSUMS = os.path.join(REPO, 'contract', 'CHECKSUMS.json')
OUT = os.path.join(
    REPO, 'app', 'src', 'main', 'java', 'com', 'resumemaster', 'android',
    'data', 'contract', 'ContractJob.kt')

# NUMERIC INTENT, WHICH THE SCHEMA DOES NOT CARRY.
#
# JSON Schema says "number" for a score, a salary and a unix timestamp alike. Decoding all three as
# Double would put "43.0" on screen and lose precision on a timestamp beyond 2^53. These overrides
# are declared here, in the open, rather than guessed field by field in the decoder.
NUMERIC_KIND = {
    'matchScore':   'Int',     # 0-100 internal score. Int because a fractional score is meaningless.
    'discoveredAt': 'Long',    # unix SECONDS per the contract description, not millis.
    'salaryMin':    'Double',
    'salaryMax':    'Double',
}


def kotlin_type(name, spec):
    t = spec.get('type')
    types = t if isinstance(t, list) else [t]
    nullable = 'null' in types
    base = next((x for x in types if x != 'null'), 'string')

    if base == 'array':
        return 'List<String>', False
    if base == 'boolean':
        return 'Boolean', nullable
    if base == 'number':
        return NUMERIC_KIND.get(name, 'Double'), nullable
    return 'String', nullable


def literal(value):
    if value is None:
        return 'null'
    if value is True:
        return 'true'
    if value is False:
        return 'false'
    if value == []:
        return 'emptyList()'
    if isinstance(value, str):
        return '"' + value + '"'
    return str(value)


def main():
    check = '--check' in sys.argv

    contract = json.load(io.open(CONTRACT, encoding='utf-8'))
    version = contract['info']['version']
    job = contract['components']['schemas']['Job']
    props = job['properties']
    required = set(job.get('required', []))

    # The generator verifies the contract it is reading, LF-normalised exactly as CHECKSUMS.json
    # instructs -- this repo is CRLF while the desktop repo runs core.autocrlf=true, so a raw-byte
    # verify fails spuriously here and would train someone to skip the check.
    sums = json.load(io.open(CHECKSUMS, encoding='utf-8'))
    raw = io.open(CONTRACT, 'rb').read().replace(b'\r\n', b'\n')
    digest = hashlib.sha256(raw).hexdigest()
    expected = sums['files']['mobile-api.v1.json']
    if digest != expected:
        sys.stderr.write('contract/mobile-api.v1.json does not match CHECKSUMS.json\n')
        sys.stderr.write('  expected ' + expected + '\n  got      ' + digest + '\n')
        return 1

    lines = []
    w = lines.append

    w('// GENERATED by scripts/generateContractModels.py from contract/mobile-api.v1.json')
    w('// (contract version ' + version + '). DO NOT HAND-EDIT -- regenerate instead.')
    w('//')
    w('// ' + str(len(props)) + ' fields. The parser this replaced carried 10, and read 5 of those')
    w('// under the wrong (snake_case) names, all of which failed silently to null.')
    w('')
    w('package com.resumemaster.android.data.contract')
    w('')
    w('import org.json.JSONObject')
    w('')
    w('data class ContractJob(')

    order = sorted(props.keys())
    for name in order:
        spec = props[name]
        ktype, nullable = kotlin_type(name, spec)
        suffix = '?' if nullable else ''
        default = ''
        if name not in required:
            default = ' = ' + ('""' if ktype == 'String' and not nullable else 'null')
        elif 'x-empty-row-value' in spec:
            ev = spec['x-empty-row-value']
            if ev is not None or nullable:
                default = ' = ' + literal(ev)
        w('  val ' + name + ': ' + ktype + suffix + default + ',')

    w(') {')
    w('  companion object {')
    w('')
    w('    /**')
    w('     * Decode one row, or return NULL if it has no usable identity.')
    w('     *')
    w('     * `id` is typed `string` by the contract but is NOT in `required`, so a row may legally')
    w('     * arrive without one. Such a row cannot be starred, disliked, applied to or')
    w('     * de-duplicated, so it is dropped here rather than rendered as a card that silently does')
    w('     * nothing. The caller counts what it dropped instead of discovering the gap later as a')
    w('     * total that disagrees with the list.')
    w('     */')
    w('    fun fromJson(o: JSONObject): ContractJob? {')
    w('      val id = o.optString("id", "")')
    w('      if (id.isEmpty()) return null')
    w('      return ContractJob(')

    for name in order:
        spec = props[name]
        ktype, nullable = kotlin_type(name, spec)
        ev = spec.get('x-empty-row-value', None)

        if ktype == 'List<String>':
            expr = 'stringList(o, "' + name + '")'
        elif ktype == 'Boolean' and not nullable:
            expr = 'o.optBoolean("' + name + '", ' + literal(ev if ev is not None else False) + ')'
        elif ktype == 'Boolean' and nullable:
            expr = 'optBooleanOrNull(o, "' + name + '")'
        elif ktype in ('Int', 'Long', 'Double') and nullable:
            expr = 'opt' + ktype + 'OrNull(o, "' + name + '")'
        elif ktype in ('Int', 'Long', 'Double'):
            expr = 'o.opt' + ktype + '("' + name + '", 0)'
        elif nullable:
            expr = 'optStringOrNull(o, "' + name + '")'
        else:
            fallback = literal(ev) if isinstance(ev, str) else '""'
            expr = 'o.optString("' + name + '", ' + fallback + ')'
        w('        ' + name + ' = ' + expr + ',')

    w('      )')
    w('    }')
    w('')
    w('    /**')
    w('     * A string, or null -- distinguishing ABSENT and JSON null from the empty string.')
    w('     *')
    w('     * org.json optString() returns "" for a missing key AND for an explicit null, so the')
    w('     * previous parser optString(...).ifEmpty { null } collapsed three different facts into')
    w('     * one. Checked explicitly here because "" is a legitimate value for several of these')
    w('     * fields and must not be laundered into null.')
    w('     */')
    w('    private fun optStringOrNull(o: JSONObject, key: String): String? =')
    w('      if (!o.has(key) || o.isNull(key)) null else o.optString(key, "")')
    w('')
    w('    private fun optBooleanOrNull(o: JSONObject, key: String): Boolean? =')
    w('      if (!o.has(key) || o.isNull(key)) null else o.optBoolean(key)')
    w('')
    w('    private fun optIntOrNull(o: JSONObject, key: String): Int? =')
    w('      if (!o.has(key) || o.isNull(key)) null else o.optInt(key)')
    w('')
    w('    private fun optLongOrNull(o: JSONObject, key: String): Long? =')
    w('      if (!o.has(key) || o.isNull(key)) null else o.optLong(key)')
    w('')
    w('    private fun optDoubleOrNull(o: JSONObject, key: String): Double? =')
    w('      if (!o.has(key) || o.isNull(key)) null else o.optDouble(key)')
    w('')
    w('    /** Always a list; [] when absent. The contract guarantees the shape, not the presence. */')
    w('    private fun stringList(o: JSONObject, key: String): List<String> {')
    w('      val arr = o.optJSONArray(key) ?: return emptyList()')
    w('      return (0 until arr.length()).mapNotNull { i ->')
    w('        if (arr.isNull(i)) null else arr.optString(i, "").ifEmpty { null }')
    w('      }')
    w('    }')
    w('  }')
    w('}')
    w('')

    text = '\r\n'.join(lines)

    if check:
        current = ''
        if os.path.exists(OUT):
            current = io.open(OUT, encoding='utf-8', newline='').read()
        if current != text:
            sys.stderr.write(OUT + ' is STALE. Run: python scripts/generateContractModels.py\n')
            return 1
        sys.stdout.write('ContractJob.kt is up to date with contract ' + version + '\n')
        return 0

    d = os.path.dirname(OUT)
    if not os.path.isdir(d):
        os.makedirs(d)
    io.open(OUT, 'w', encoding='utf-8', newline='').write(text)
    sys.stdout.write('wrote ' + OUT + ' (' + str(len(props)) + ' fields, contract ' + version + ')\n')
    return 0


if __name__ == '__main__':
    sys.exit(main())
